### ISSUE TITLE
Using Username/Password authorization when extending Herbie

### ISSUE THREAD

**Issue by isodrosotherm** [blaylockbk/Herbie#51]
I'm trying to add IMERG to the list of models. To download the data one must register with NASA and then use a username/password to access the data.

Typically I've gotten the data using python through a url using this format `https://username:password@URL` however when I add that style of url to the model's self.SOURCES I get the following Traceback 
```
Traceback (most recent call last):
  File "herbie_methods.py", line 37, in <module>
    H.download(verbose=False)
  File "/Users/judson/opt/anaconda3/envs/main/lib/python3.8/site-packages/herbie/archive.py", line 642, in download
    urllib.request.urlretrieve(self.grib, outFile, _reporthook)
  File "/Users/judson/opt/anaconda3/envs/main/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Users/judson/opt/anaconda3/envs/main/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/judson/opt/anaconda3/envs/main/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Users/judson/opt/anaconda3/envs/main/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Users/judson/opt/anaconda3/envs/main/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Users/judson/opt/anaconda3/envs/main/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Users/judson/opt/anaconda3/envs/main/lib/python3.8/urllib/request.py", line 1323, in do_open
    h = http_class(host, timeout=req.timeout, **http_conn_args)
  File "/Users/judson/opt/anaconda3/envs/main/lib/python3.8/http/client.py", line 1383, in __init__
    super(HTTPSConnection, self).__init__(host, port, timeout,
  File "/Users/judson/opt/anaconda3/envs/main/lib/python3.8/http/client.py", line 834, in __init__
    (self.host, self.port) = self._get_hostport(host, port)
  File "/Users/judson/opt/anaconda3/envs/main/lib/python3.8/http/client.py", line 877, in _get_hostport
    raise InvalidURL("nonnumeric port: '%s'" % host[i+1:])
http.client.InvalidURL: nonnumeric port: 'password@jsimpsonhttps.pps.eosdis.nasa.gov'
``` 

Is there a way around this, or should I add the username/password differently?

**Comment by blaylockbk** [comment]
Thanks for the question. That's interesting you want to use Herbie to download IMERG data. Herbie was built to download GRIB files, but the framework might be able to download any type of file, even IMERG.

So, how do you usually download IMERG files from `https://username:password@URL` with Python? Herbie uses both the requests and urllib library.

Here, Herbie uses urllib to download a full file in the following line:
https://github.com/blaylockbk/Herbie/blob/4baae6f1ecb4749249dd36fe4822738be02832d5/herbie/archive.py#L860
- `self.grib` is the URL for a grib file. 
- `outFile` is destination of the file (where the file is download)

Also, Herbie uses the requests library to check that a file exists before downloading it
https://github.com/blaylockbk/Herbie/blob/4baae6f1ecb4749249dd36fe4822738be02832d5/herbie/archive.py#L457-L465

Does your `https://username:password@URL` work with both those libraries?
```python
import urllib.request
import request
urllib.request.urlretrieve("https://username:password@URL", "outfile")
requests.head("https://username:password@URL").ok
```

**Comment by isodrosotherm** [comment]
We just love Herbie so much, we've been trying to extend it to as many downloads as possible 😄 it seems like the issue is with `urllib.request` where that nonnumeric port error is being thrown. No worries as this seems to be outside the scope of Herbie. Thanks a bunch for helping look into it!

**Comment by blaylockbk** [comment]
Glad you like Herbie! I'm curious, have you had success extending it for other downloads?

**Comment by isodrosotherm** [comment]
so far just GEFS, but it worked like a charm!
